server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: product_user
    password: product_pass
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.yuzarsif.productcatalogueservice.config

elasticsearch:
  hosts: ${ELASTICSEARCH_HOSTS:http://localhost:9200}
  index:
    products: ${ELASTICSEARCH_INDEX_PRODUCTS:products-v1}
